spring.application.name=Spring-Boot

# 1. C\u1EA5u h\u00ECnh k\u1EBFt n\u1ED1i PostgreSQL (Kh\u1EDBp 100% v\u1EDBi Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/telusko1
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. B\u00F9a ch\u00FA JPA / Hibernate (Quan tr\u1ECDng \u0111\u1EC3 fix l\u1ED7i Dialect)
# \u00C9p n\u00F3 nh\u1EADn di\u1EC7n \u0111\u00FAng ng\u00F4n ng\u1EEF PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# T\u1EF1 \u0111\u1ED9ng t\u1EA1o b\u1EA3ng d\u1EF1a tr\u00EAn class @Entity (N\u1EBFu ch\u01B0a c\u00F3 b\u1EA3ng users n\u00F3 s\u1EBD t\u1EF1 \u0111\u1EBB ra)
spring.jpa.hibernate.ddl-auto=update

# 3. Hi\u1EC7n c\u00E2u l\u1EC7nh SQL ra m\u00E0n h\u00ECnh \u0111\u1EC3 soi l\u1ED7i
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
