spring.application.name=Spring-Boot

# URL k?t n?i ??n DB H2 (l?u trên RAM, tên là telusko)
spring.datasource.url=jdbc:h2:mem:dave

# Tên Class Driver (Th?c ra Spring Boot b?n m?i t? nh?n, nh?ng ghi cho ch?c)
spring.datasource.driverClassName=org.h2.Driver

# Username/Password m?c ??nh c?a H2
spring.datasource.username=dave
spring.datasource.password=

# B?t cái giao di?n qu?n lý DB trên trình duy?t lên (Quan tr?ng ?? soi data)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console