spring.application.name=Spring-Boot

# C\u1EA5u h\u00ECnh MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/telusko_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# oauth 2.0 github
spring.security.oauth2.client.registration.github.client-id=Ov23lieTXQMcqaOhZN7O
spring.security.oauth2.client.registration.github.client-secret=262d430f8b00cec2cbfac2babf59a8db774d368a